#### Library

In [1]:
import pandas as pd
import random

In [2]:
# read the data from the downloaded CSV file.
data = pd.read_csv('https://s3-eu-west-1.amazonaws.com/shanebucket/downloads/uk-500.csv')
# set a numeric id for use as an index for examples.
data['id'] = [random.randint(0,1000) for x in range(data.shape[0])]
 
data.head(5)

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,270
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,734
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,569
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,171
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,605

In [3]:
# Single selections using iloc and DataFrame
# Rows:
data.iloc[0] # first row of data frame (Aleshia Tomkiewicz) - Note a Series data type output.

first_name                                   Aleshia
last_name                                 Tomkiewicz
company_name                 Alan D Rosenburg Cpa Pc
address                                 14 Taylor St
city                               St. Stephens Ward
county                                          Kent
postal                                       CT2 7PP
phone1                                  01835-703597
phone2                                  01944-369967
email                        atomkiewicz@hotmail.com
web             http://www.alandrosenburgcpapc.co.uk
id                                               270
Name: 0, dtype: object

In [4]:
data.iloc[1] # second row of data frame (Evan Zigomalas)

first_name                                   Evan
last_name                               Zigomalas
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
id                                            734
Name: 1, dtype: object

In [5]:
data.iloc[-1] # last row of data frame (Mi Richan)

first_name                                               Mi
last_name                                            Richan
company_name                 Nelson Wright Haworth Golf Crs
address                                     6 Norwood Grove
city                                      Tanworth-in-Arden
county                                         Warwickshire
postal                                              B94 5RZ
phone1                                         01451-785624
phone2                                         01202-738406
email                                        mi@hotmail.com
web             http://www.nelsonwrighthaworthgolfcrs.co.uk
id                                                      806
Name: 499, dtype: object

In [6]:
# Columns:
data.iloc[:,0] # first column of data frame (first_name)

0        Aleshia
1           Evan
2         France
3        Ulysses
4         Tyisha
         ...
495        Avery
496         Reid
497    Charlette
498    Celestina
499           Mi
Name: first_name, Length: 500, dtype: object

In [7]:
data.iloc[:,1] # second column of data frame (last_name)

0      Tomkiewicz
1       Zigomalas
2         Andrade
3       Mcwalters
4          Veness
          ...
495          Veit
496       Euresti
497      Brenning
498         Keeny
499        Richan
Name: last_name, Length: 500, dtype: object

In [8]:
data.iloc[:,-1] # last column of data frame (id)

0      270
1      734
2      569
3      171
4      605
      ...
495    439
496    353
497    668
498    462
499    806
Name: id, Length: 500, dtype: int64

In [9]:
# Multiple row and column selections using iloc and DataFrame
data.iloc[0:5] # first five rows of dataframe

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,270
1,Evan,Zigomalas,Cap Gemini America,5 Binney St,Abbey Ward,Buckinghamshire,HP11 2AX,01937-864715,01714-737668,evan.zigomalas@gmail.com,http://www.capgeminiamerica.co.uk,734
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,569
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,171
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,605

In [10]:
data.iloc[:, 0:2] # first two columns of data frame with all rows

    first_name   last_name
0      Aleshia  Tomkiewicz
1         Evan   Zigomalas
2       France     Andrade
3      Ulysses   Mcwalters
4       Tyisha      Veness
..         ...         ...
495      Avery        Veit
496       Reid     Euresti
497  Charlette    Brenning
498  Celestina       Keeny
499         Mi      Richan

[500 rows x 2 columns]

In [11]:
data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.

   first_name        county    postal
0     Aleshia          Kent   CT2 7PP
3     Ulysses  Lincolnshire  DN36 5RP
6        Marg   Southampton  SO14 3TY
24       Tess   West Sussex  PO19 1RH

In [12]:
data.iloc[0:5, 5:8] # first 5 rows and 5th, 6th, 7th columns of data frame (county -> phone1).

            county    postal        phone1
0             Kent   CT2 7PP  01835-703597
1  Buckinghamshire  HP11 2AX  01937-864715
2      Bournemouth   BH6 3BE  01347-368222
3     Lincolnshire  DN36 5RP  01912-771311
4    West Midlands   B70 9DT  01547-429341

In [13]:
# Select rows with first name Antonio, # and all columns between 'city' and 'email'
data.loc[data['first_name'] == 'Antonio', 'city':'email']

,city,county,postal,phone1,phone2,email
272,Little Parndon and Hare Street,Hertfordshire,CM20 2HT,01559-403415,01388-777812,antonio.villamarin@gmail.com
285,Gaer Community,Newport,NP20 3DE,01463-409090,01242-318420,antonio_glasford@glasford.co.uk
427,Ipplepen,Devon,TQ12 5LL,01324-171614,01442-946357,antonio.heilig@gmail.com

In [14]:
# Select rows where the email column ends with 'hotmail.com', include all columns
data.loc[data['email'].str.endswith("hotmail.com")]

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
0,Aleshia,Tomkiewicz,Alan D Rosenburg Cpa Pc,14 Taylor St,St. Stephens Ward,Kent,CT2 7PP,01835-703597,01944-369967,atomkiewicz@hotmail.com,http://www.alandrosenburgcpapc.co.uk,270
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,569
3,Ulysses,Mcwalters,"Mcmahan, Ben L",505 Exeter Rd,Hawerby cum Beesby,Lincolnshire,DN36 5RP,01912-771311,01302-601380,ulysses@hotmail.com,http://www.mcmahanbenl.co.uk,171
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,605
6,Marg,Grasmick,Wrangle Hill Auto Auct & Slvg,7457 Cowl St #70,Bargate Ward,Southampton,SO14 3TY,01865-582516,01362-620532,marg@hotmail.com,http://www.wranglehillautoauctslvg.co.uk,896
...,...,...,...,...,...,...,...,...,...,...,...,...
486,Sophia,Gaucher,T C E Systems Inc,88 Upper Harrington St,North East Ward,North Lanarkshire,G69 8EL,01504-539114,01254-919378,sophia.gaucher@hotmail.com,http://www.tcesystemsinc.co.uk,709
490,Rosita,Ausdemore,"Jurdem, Scott Esq",8 Heathfield St #657,Hailsham,East Sussex,BN27 1AJ,01273-236188,01997-765432,rausdemore@hotmail.com,http://www.jurdemscottesq.co.uk,873
491,Huey,Stancil,Lindner Funds,275 Peel Sq,Park Ward,North Eart Lincolnshire,DN32 0PT,01502-139578,01468-195646,hstancil@hotmail.com,http://www.lindnerfunds.co.uk,356
492,Elbert,Fiorino,"Donald, G Nelson Esq",726 Westmoreland Place,Ballochmyle Ward,East Ayrshire,KA5 6EL,01724-467889,01992-537553,elbert@hotmail.com,http://www.donaldgnelsonesq.co.uk,522
499,Mi,Richan,Nelson Wright Haworth Golf Crs,6 Norwood Grove,Tanworth-in-Arden,Warwickshire,B94 5RZ,01451-785624,01202-738406,mi@hotmail.com,http://www.nelsonwrighthaworthgolfcrs.co.uk,806

In [15]:
# Select rows with last_name equal to some values, all columns
data.loc[data['first_name'].isin(['France', 'Tyisha', 'Eric'])]

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,569
4,Tyisha,Veness,Champagne Room,5396 Forth Street,Greets Green and Lyng Ward,West Midlands,B70 9DT,01547-429341,01290-367248,tyisha.veness@hotmail.com,http://www.champagneroom.co.uk,605
5,Eric,Rampy,"Thompson, Michael C Esq",9472 Lind St,Desborough,Northamptonshire,NN14 2GH,01969-886290,01545-817375,erampy@rampy.co.uk,http://www.thompsonmichaelcesq.co.uk,137

In [16]:
# Select rows with first name Antonio AND hotmail email addresses
data.loc[data['email'].str.endswith("gmail.com") & (data['first_name'] == 'Antonio')]

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
272,Antonio,Villamarin,Combs Sheetmetal,353 Standish St #8264,Little Parndon and Hare Street,Hertfordshire,CM20 2HT,01559-403415,01388-777812,antonio.villamarin@gmail.com,http://www.combssheetmetal.co.uk,36
427,Antonio,Heilig,Radisson Suite Hotel,35 Elton St #3,Ipplepen,Devon,TQ12 5LL,01324-171614,01442-946357,antonio.heilig@gmail.com,http://www.radissonsuitehotel.co.uk,480

In [17]:
# select rows with id column between 100 and 200, and just return 'postal' and 'web' columns
data.loc[(data['id'] > 100) & (data['id'] <= 200), ['postal', 'web']]

       postal                                           web
3    DN36 5RP                  http://www.mcmahanbenl.co.uk
5    NN14 2GH          http://www.thompsonmichaelcesq.co.uk
8    BS16 4LL                http://www.bizerbausainc.co.uk
19    TQ3 1SA        http://www.gallowayelectriccoinc.co.uk
42    TR9 6NJ               http://www.frankelstephen.co.uk
54   BN20 7HB                   http://www.bomarkoinc.co.uk
74   TN26 2PN     http://www.burgesssteelproductscorp.co.uk
77   CA17 4RZ                http://www.jonsongeodesq.co.uk
78    ST2 9AW      http://www.daleyoderclulifehlthbus.co.uk
90    RG7 3RA            http://www.eastcountyprocess.co.uk
113  AB53 6YD      http://www.manhattansupplycodeerpk.co.uk
134   M32 8LR                      http://www.fanshop.co.uk
143  PL31 1QF            http://www.thompsonchesneymd.co.uk
160  LA14 3SJ         http://www.callenderwilliamcesq.co.uk
164   NW5 4EU                http://www.desktopcenter.co.uk
171    S5 8LL   http://www.genevawoodsprofessionalctr.co.uk
181  LL54 7UP                http://www.matamarioaesq.co.uk
183   SR8 5RL  http://www.philosophicalrsrchsctybkstr.co.uk
187  SE19 2TJ            http://www.elmarkgraphicsinc.co.uk
189   BL1 6DS               http://www.mmmdesigngroup.co.uk
197  KY14 6AH       http://www.mcmahanmcmahanbrinkley.co.uk
209   CV6 4BN             http://www.sadowskijeffreya.co.uk
212  CT14 9QJ         http://www.pigeonfallsstatebank.co.uk
219   BN2 4TL          http://www.charlesscavadinicic.co.uk
220   BS7 0AX            http://www.hydricklawoffices.co.uk
231  SW19 7DT            http://www.transbaysteelcorp.co.uk
232  SK14 5AR               http://www.severttodddesq.co.uk
236  HP11 2PJ                      http://www.wuhffox.co.uk
260  RH10 8EZ           http://www.mnplsarprtmarriott.co.uk
288  EH42 1SJ                   http://www.mrbarbqinc.co.uk
292   BS6 5SR     http://www.geminihatsaccessoriesinc.co.uk
301   B36 8JE        http://www.graniteconstructionco.co.uk
304  HU11 4QA             http://www.millermartinmesq.co.uk
311   FY8 3TF                 http://www.nursefinders.co.uk
322   M22 4ZB       http://www.newrivertirecompanyinc.co.uk
324  NE11 0AN            http://www.nohrkatharinemesq.co.uk
347  BD15 0NJ               http://www.finleycolmerco.co.uk
353   ML1 4TD             http://www.benderassociates.co.uk
382   PR3 0UH        http://www.toolservicecompanyinc.co.uk
394   NN8 4DR            http://www.ariasmicheleannmd.co.uk
415   SR7 0AZ        http://www.hasselbergmichaelresq.co.uk
417  GL50 2LF   http://www.daviscommercialcontracting.co.uk
424   LS1 8HZ                      http://www.ezaksco.co.uk
429   ST9 0AH               http://www.elhispanicnews.co.uk
431  BA13 3QR                  http://www.kenneymfgco.co.uk
435   N12 0EF           http://www.mcknighthvincentjr.co.uk
456  ME18 6JE     http://www.guldstrandengineeringinc.co.uk
476  NG15 8DD               http://www.fredanthonyesq.co.uk
482   RG1 9XH               http://www.kellerraymondc.co.uk

In [18]:
# A lambda function that yields True/False values can also be used.
# Select rows where the company name has 4 words in it.
data.loc[data['company_name'].apply(lambda x: len(x.split(' ')) == 4)]

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
2,France,Andrade,"Elliott, John W Esq",8 Moor Place,East Southbourne and Tuckton W,Bournemouth,BH6 3BE,01347-368222,01935-821636,france.andrade@hotmail.com,http://www.elliottjohnwesq.co.uk,569
5,Eric,Rampy,"Thompson, Michael C Esq",9472 Lind St,Desborough,Northamptonshire,NN14 2GH,01969-886290,01545-817375,erampy@rampy.co.uk,http://www.thompsonmichaelcesq.co.uk,137
11,Charlesetta,Erm,"Cain, John M Esq",5 Hygeia St,Loundsley Green Ward,Derbyshire,S40 4LY,01276-816806,01517-624517,charlesetta_erm@gmail.com,http://www.cainjohnmesq.co.uk,780
15,Michell,Throssell,Weiss Spirt & Guyer,89 Noon St,Carbrooke,Norfolk,IP25 6JQ,01967-580851,01672-496478,mthrossell@throssell.co.uk,http://www.weissspirtguyer.co.uk,555
16,Edgar,Kanne,"Crowan, Kenneth W Esq",99 Guthrie St,New Milton,Hampshire,BH25 5DF,01326-532337,01666-638176,edgar.kanne@yahoo.com,http://www.crowankennethwesq.co.uk,969
...,...,...,...,...,...,...,...,...,...,...,...,...
481,Ahmad,Alsaqri,Alliance Construction Co Inc,21 Pickwick St,Sutton cum Duckmanton,Derbyshire,S44 5DS,01567-555570,01852-550588,ahmad.alsaqri@yahoo.com,http://www.allianceconstructioncoinc.co.uk,490
484,Jacquelyne,Reibman,Great Clips For Hair,70 Lilly Rd,Shirley Ward,Greater London,CR0 7PT,01846-581451,01850-754504,jacquelyne_reibman@yahoo.com,http://www.greatclipsforhair.co.uk,697
487,Isabelle,Kono,Rock Springs Petroleum Equip,4920 Fazakerley Rd,Plymstock Dunstone Ward,Devon,PL9 8RD,01552-682601,01953-816728,isabelle.kono@yahoo.com,http://www.rockspringspetroleumequip.co.uk,33
492,Elbert,Fiorino,"Donald, G Nelson Esq",726 Westmoreland Place,Ballochmyle Ward,East Ayrshire,KA5 6EL,01724-467889,01992-537553,elbert@hotmail.com,http://www.donaldgnelsonesq.co.uk,522
498,Celestina,Keeny,Bfg Federal Credit Union,9 Milton St,Consett North ED,County Durham,DH8 5LP,01877-379681,01600-463475,celestina_keeny@gmail.com,http://www.bfgfederalcreditunion.co.uk,462

In [19]:
# Selections can be achieved outside of the main .loc for clarity:
# Form a separate variable with your selections:
idx = data['company_name'].apply(lambda x: len(x.split(' ')) == 4)

In [20]:
# Select only the True values in 'idx' and only the 3 columns specified:
data.loc[idx, ['email', 'first_name', 'web']]

,email,first_name,web
2,france.andrade@hotmail.com,France,http://www.elliottjohnwesq.co.uk
5,erampy@rampy.co.uk,Eric,http://www.thompsonmichaelcesq.co.uk
11,charlesetta_erm@gmail.com,Charlesetta,http://www.cainjohnmesq.co.uk
15,mthrossell@throssell.co.uk,Michell,http://www.weissspirtguyer.co.uk
16,edgar.kanne@yahoo.com,Edgar,http://www.crowankennethwesq.co.uk
...,...,...,...
481,ahmad.alsaqri@yahoo.com,Ahmad,http://www.allianceconstructioncoinc.co.uk
484,jacquelyne_reibman@yahoo.com,Jacquelyne,http://www.greatclipsforhair.co.uk
487,isabelle.kono@yahoo.com,Isabelle,http://www.rockspringspetroleumequip.co.uk
492,elbert@hotmail.com,Elbert,http://www.donaldgnelsonesq.co.uk
498,celestina_keeny@gmail.com,Celestina,http://www.bfgfederalcreditunion.co.uk

In [21]:
# Change the first name of all rows with an ID greater than 2000 to "John"
data.loc[data['id'] > 2000, "first_name"] = "John"

In [22]:
data.loc[data['id'] < 100].value_counts('county')

county
West Yorkshire             4
Tyne and Wear              3
Kent                       3
Cheshire                   2
Rhondda Cynon Taff         2
Wiltshire                  2
Devon                      2
West Midlands              2
Greater Manchester         2
Surrey                     2
South Yorkshire            2
Shropshire                 2
Warwickshire               1
Stoke-on-Trent             1
Stirling                   1
Staffordshire              1
Northumberland             1
Nottinghamshire            1
Denbighshire               1
North Eart Lincolnshire    1
Newport                    1
Middlesbrough              1
Hertfordshire              1
Hereford and Worcester     1
Hampshire                  1
Greater London             1
Flintshire                 1
East Dunbartonshire        1
Derbyshire                 1
Yorkshire, South           1
dtype: int64

In [23]:
data.loc[data['id'] < 100].sort_values('county')

,first_name,last_name,company_name,address,city,county,postal,phone1,phone2,email,web,id
329,Carmen,Gillham,"Norda, Beth Dorsey Esq",11 Denison St #7,Orford Ward,Cheshire,WA2 9QB,01692-491267,01417-973243,carmen@hotmail.com,http://www.nordabethdorseyesq.co.uk,51
65,Lindsay,Yadao,"Lutz, Christopher T Esq",7 Jolliffe St,Middlewich,Cheshire,CW10 9GB,01947-566661,01481-295251,lindsay_yadao@yadao.co.uk,http://www.lutzchristophertesq.co.uk,48
20,Peter,Gutierres,Niagara Custombuilt Mfg Co,4410 Tarlton St,Prestatyn Community,Denbighshire,LL19 9EG,01842-767201,01859-648598,peter_gutierres@yahoo.com,http://www.niagaracustombuiltmfgco.co.uk,15
87,Jeannetta,Coolidge,Tiny Tots Originals Div,761 Cockerell St #1,Midway Ward,Derbyshire,DE11 0HE,01927-790069,01440-276155,jeannetta_coolidge@gmail.com,http://www.tinytotsoriginalsdiv.co.uk,25
108,Kyoko,Mcmillian,Nature Conservancy,77 Reading St #8,North Tawton,Devon,EX20 2TR,01235-173362,01371-735347,kyoko_mcmillian@gmail.com,http://www.natureconservancy.co.uk,59
487,Isabelle,Kono,Rock Springs Petroleum Equip,4920 Fazakerley Rd,Plymstock Dunstone Ward,Devon,PL9 8RD,01552-682601,01953-816728,isabelle.kono@yahoo.com,http://www.rockspringspetroleumequip.co.uk,33
362,Stefania,Weatherwax,Robert Vance Ltd,25 Dale St #2,Kirkintilloch East and Twechar,East Dunbartonshire,G66 3LX,01698-705920,01879-295373,sweatherwax@yahoo.com,http://www.robertvanceltd.co.uk,54
250,Isidra,Varnado,Howland Machine Corp,79 Chelmsford St,Holywell Community,Flintshire,CH8 7UP,01600-982590,01591-464964,ivarnado@varnado.co.uk,http://www.howlandmachinecorp.co.uk,85
276,Kenda,Koza,General Bindery Co Inc,7 Netley St,Custom House Ward,Greater London,E16 3DP,01840-188852,01476-264977,kkoza@koza.co.uk,http://www.generalbinderycoinc.co.uk,44
84,Una,Frankel,Shamrock Food Service,6766 Britton St #379,Crompton Ward,Greater Manchester,BL1 3EX,01912-749219,01308-356704,ufrankel@hotmail.com,http://www.shamrockfoodservice.co.uk,2
386,Elmira,Ringlein,"Hyland, Richard S Esq",143 Clark St #802,Halliwell Ward,Greater Manchester,BL1 2PS,01934-672498,01347-140077,eringlein@gmail.com,http://www.hylandrichardsesq.co.uk,12
85,Eva,Joulwan,Central Hrdwr & Elec Corp,7 Lear Rd,Stroud,Hampshire,GU32 3PQ,01779-720349,01961-802899,eva.joulwan@gmail.com,http://www.centralhrdwreleccorp.co.uk,47
352,Melvin,Setter,Rex Internatl,87 Pickup St,Franche Ward,Hereford and Worcester,DY10 2ZQ,01401-151569,01938-566719,melvin_setter@setter.co.uk,http://www.rexinternatl.co.uk,96
272,Antonio,Villamarin,Combs Sheetmetal,353 Standish St #8264,Little Parndon and Hare Street,Hertfordshire,CM20 2HT,01559-403415,01388-777812,antonio.villamarin@gmail.com,http://www.combssheetmetal.co.uk,36
118,Paola,Dease,Sunderland Publishing Co,94 Enid St,Birchington,Kent,CT7 9BG,01333-642646,01419-231768,pdease@gmail.com,http://www.sunderlandpublishingco.co.uk,67
163,Thad,Puskarich,"Drubner, Norman S Esq",9302 Ismay St #6,Tenterden,Kent,TN30 6JP,01506-152661,01686-258819,thad_puskarich@puskarich.co.uk,http://www.drubnernormansesq.co.uk,60
444,Paul,Farrin,"Dering, James E Esq",7 Varthen St,Town Ward,Kent,DA1 2DL,01407-775572,01879-963638,paul.farrin@farrin.co.uk,http://www.deringjameseesq.co.uk,38
67,Stefany,Ferenz,L & L Sales Co Inc,636 Portland Place,Gresham Ward,Middlesbrough,TS1 4RG,01743-977277,01704-986828,stefany@hotmail.com,http://www.llsalescoinc.co.uk,57
285,Antonio,Glasford,Saint Thomas Creations,425 Howley St,Gaer Community,Newport,NP20 3DE,01463-409090,01242-318420,antonio_glasford@glasford.co.uk,http://www.saintthomascreations.co.uk,97
26,Svetlana,Tauras,"Lensbower, Gregory L Esq",8289 Cadogan St,South Ward,North Eart Lincolnshire,DN33 1AU,01781-827317,01509-121140,svetlana_tauras@tauras.co.uk,http://www.lensbowergregorylesq.co.uk,16
441,Felice,Gone,A F Supl Co Div Automtc Firing,7602 Grantham St,Hexham,Northumberland,NE46 1QQ,01691-816025,01888-857515,felice.gone@hotmail.com,http://www.afsuplcodivautomtcfiring.co.uk,1
399,Brynn,Capra,Magic Valley Irrigation Supply,488 Mulberry St,Ravenshead,Nottinghamshire,NG15 9AE,01963-124789,01702-314016,brynn_capra@yahoo.com,http://www.magicvalleyirrigationsupply.co.uk,1
60,Maybelle,Consolazio,"Gavin, Lee W Esq",5410 Lawton St,Treorchy Community,Rhondda Cynon Taff,CF42 6PL,01383-647035,01351-200904,mconsolazio@yahoo.com,http://www.gavinleewesq.co.uk,94
416,Arlean,Calaf,Ed Miniat Inc,82 Waterhouse Lane,Llantrisant Community,Rhondda Cynon Taff,CF72 8LB,01448-395723,01407-700390,acalaf@yahoo.com,http://www.edminiatinc.co.uk,86
33,Luis,Ear,Wa Inst For Plcy Studies,2 Birchfield Rd,Whittington,Shropshire,SY11 4PH,01462-648669,01405-648623,luis@hotmail.com,http://www.wainstforplcystudies.co.uk,86
178,Dacia,Swaisgood,Nelson & Paulson Chartered,36 Cranmer St #4697,Little Hereford,Shropshire,SY8 4LE,01984-926059,01275-123842,dacia.swaisgood@swaisgood.co.uk,http://www.nelsonpaulsonchartered.co.uk,62
443,Margarita,Orloski,1893 Shops,78 Pine Grove,Stannington Ward,South Yorkshire,S6 5HE,01215-422453,01958-497953,margarita_orloski@yahoo.com,http://www.shops.co.uk,5
309,Janna,Przybyl,Southwest Ms Shopg Bag,5 April Rd #13,Wheatley Ward,South Yorkshire,DN1 2TU,01684-628072,01560-680129,jprzybyl@przybyl.co.uk,http://www.southwestmsshopgbag.co.uk,20
281,Olen,Ailey,"Shohet, Grace C Esq",9 Fielding St,Wombourne,Staffordshire,WV5 0BB,01654-865551,01354-169004,olen@gmail.com,http://www.shohetgracecesq.co.uk,91
323,Launa,Torez,"Farber, Mindy Esq",12 Gelling St,Trossachs and Teith Ward,Stirling,FK16 6DU,01670-547878,01919-422541,launa.torez@yahoo.com,http://www.farbermindyesq.co.uk,0
238,Cruz,Fanelli,"Graham, John A Esq",4565 Blackstock St,Springfields and Trent Vale Wa,Stoke-on-Trent,ST4 5BW,01710-616480,01314-202428,cruz@hotmail.com,http://www.grahamjohnaesq.co.uk,14
310,Emiko,Sayre,Scott Marlow Agency,8 Village St,Windlesham,Surrey,GU18 5YQ,01660-135336,01348-284404,emiko.sayre@yahoo.com,http://www.scottmarlowagency.co.uk,13
377,Theron,Merriam,"Percival, Mark R Esq",869 Luke St,Wonersh,Surrey,GU5 0QU,01655-809574,01859-311417,theron@merriam.co.uk,http://www.percivalmarkresq.co.uk,21
126,Beth,Barbone,Upper Deck Co,3 Gaskell St,Tynemouth Ward,Tyne and Wear,NE30 2NB,01210-926114,01521-151330,bbarbone@barbone.co.uk,http://www.upperdeckco.co.uk,12
434,Cherelle,Sorrel,"Wiltgen, Nancy A Esq",794 Hook St,Benwell and Scotswood Ward,Tyne and Wear,NE15 7JA,01753-327307,01212-458253,cherelle_sorrel@gmail.com,http://www.wiltgennancyaesq.co.uk,10
167,Eileen,Montecalvo,Holiday House Apts,9986 Cantsfield St,St. Peters Ward,Tyne and Wear,SR6 9SD,01904-227024,01278-578708,eileen@yahoo.com,http://www.holidayhouseapts.co.uk,52
407,Sunshine,Senechal,"Dale, George F Esq",40 Cairo St,Warwick,Warwickshire,CV34 5LQ,01416-686933,01839-700945,sunshine.senechal@hotmail.com,http://www.dalegeorgefesq.co.uk,71
312,Eleni,Vanscoik,"Simpson, Fred B Esq",9 Mather St,Sutton Vesey Ward,West Midlands,B73 6HH,01208-373467,01628-638196,eleni_vanscoik@gmail.com,http://www.simpsonfredbesq.co.uk,15
367,Laquanda,Kho,Bayou Welding Works Inc,7 Lockhart St,Billesley Ward,West Midlands,B14 5HS,01725-370369,01271-465942,laquanda.kho@yahoo.com,http://www.bayouweldingworksinc.co.uk,8
335,Cristina,Marola,Pro Img Mktng & Pub Rel Inc,2449 Amberly St #6364,Temple Newsam Ward,West Yorkshire,LS15 0PQ,01264-145506,01538-230493,cmarola@gmail.com,http://www.proimgmktngpubrelinc.co.uk,72
161,Phillip,Aloi,"Duffield, Michael C",6 Cannock St,Scarcroft,West Yorkshire,LS14 3BW,01490-898175,01867-710914,paloi@hotmail.com,http://www.duffieldmichaelc.co.uk,36
390,Angelica,Poisso,Chemical Consultants,47 Orry St #8243,Castleford Central and Glassho,West Yorkshire,WF10 4DW,01472-449327,01758-700994,apoisso@gmail.com,http://www.chemicalconsultants.co.uk,13
247,Daryl,Hilcher,Petaluma Area Chamber Commrce,6267 Greenland St,Wakefield East Ward,West Yorkshire,WF1 4LW,01391-238570,01517-862819,dhilcher@hotmail.com,http://www.petalumaareachambercommrce.co.uk,51
371,Jeff,Brossoit,Jeh Construction Co,954 Madelaine St,Central Ward,Wiltshire,SN5 8WG,01593-501965,01383-683074,jeff.brossoit@yahoo.com,http://www.jehconstructionco.co.uk,44
389,Ronna,Mittler,Bethesda Gazette,2767 Pembroke St #979,Roundway,Wiltshire,SN10 3FQ,01214-651738,01794-156776,ronna_mittler@hotmail.com,http://www.bethesdagazette.co.uk,7
18,Charisse,Spinello,Modern Plastics Corp,9165 Primrose St,Darnall Ward,"Yorkshire, South",S4 7WN,01719-831436,01207-428520,charisse_spinello@spinello.co.uk,http://www.modernplasticscorp.co.uk,97